[workspace]
name = "patched-kushion"
channels = ["https://prefix.dev/github-releases", "conda-forge"]
platforms = ["linux-64", "win-64"]
requires-pixi = ">=0.76.2"

[dependencies]
python = "*"
graalvm = ">=25.2.4,<26"

[pypi-dependencies]
fdroidserver = ">=2.4.5, <3"
